// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type List struct {
	ID        string
	Title     string
	UserID    string
	CreatedAt pgtype.Timestamptz
}

type Todo struct {
	ID        string
	Text      string
	Completed bool
	ListID    string
	UserID    string
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        string
	Username  string
	Password  string
	CreatedAt pgtype.Timestamptz
}
